[package]
name = "mellos-kernel"
version = "0.8.0-development-p2"
edition = "2021"

[dependencies]
limine = "0.5"
spin = "0.10"
x86_64 = "0.15"
bitflags = "2.4"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
